name: models
description: Nostr models in Dart
version: 0.0.1
repository: https://github.com/purplebase/models

environment:
  sdk: ^3.6.1

dependencies:
  riverpod: ^2.6.1
  equatable: ^2.0.7
  collection: ^1.19.0
  convert: ^3.1.2
  bip340: ^0.3.0
  bech32: ^0.2.2
  crypto: ^3.0.6
  faker: ^2.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
